#!/usr/bin/perl -w
use strict;

use lib qw(../blib/lib ./blib/lib);
use Algorithm::MarkovChain::MLDBM;

use MLDBM qw(GDBM_File Storable);
use Fcntl;

tie my %mldbm, 'MLDBM', 'testdbm', O_CREAT|O_RDWR, 0644
  or die $!;

my $mc = Algorithm::MarkovChain->new(chains => \%mldbm);

my $infile = shift;
if ($infile) {
    $| = 1;
    print "seeding from $infile\n";

    open IN, $infile;
    while (<IN>) {
        $mc->seed(symbols => [m/(\S+)/g],
                  longest => 4);
        print "\r$.        ";
    }
    print "\nseeded\n";
}


while (<>) {
    print join(' ', $mc->spew(length => 30)),"\n";
}
